version: '3.0'

services:
  nginx:
    restart: always
    image: nginx:1.11.6-alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - /usr/local/software/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/localtime:/etc/localtime
      - /var/log/nginx:/var/log/nginxpwd